# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.7"
  - "3.6"
  - "2.7"
  - "pypy"

install:
  - pip install -U -r requirements-dev.txt
  - pip install coveralls

script:
  make check

after_success:
  coveralls

sudo: false
